browser=chrome
base.url=https://cjm-projects.github.io/Hobby-Hub/#/
explicit.wait.seconds=20
results.url=https://cjm-projects.github.io/Hobby-Hub/#/quiz-results?active=1&creative=1&relaxing=4&social=5&outdoor=4&strategic=1&price=5&timeCommitment=2